### ISSUE TITLE
Bug: Vertical images hide the navigation tools on mobile

### ISSUE THREAD

**Issue by lbesson** [c2corg/c2c_ui#1315]
**Describe the bug**
Vertical images hide the navigation tools on mobile

**Expected behavior**
Tools should not be partially hidden.

**Screenshots**
![localhost_8080_outings_1231828_fr_gloppefoss-en-aller-retour- (2)](https://user-images.githubusercontent.com/127776/88942034-020dcc80-d28a-11ea-9db0-607f28346143.png)

**Additional context**
Possible reason: the navigation element is accounted here https://github.com/c2corg/c2c_ui/blob/master/src/components/image-viewer/ImageViewer.vue#L272 but is hidden on mobile.
Maybe use bulma breakpoint for this line

**Comment by eddy-geek** [comment]
I came across this from `git blame` as I find there is now a ton of lost space...

![image](https://github.com/c2corg/c2c_ui/assets/2772505/1241e238-4f45-49d7-8517-e7770bee74fc)

- Big title bar even when no title
   -  even when there is one, I would personally prefer it as overlay at least in this case (mobile in landscape orientation)
- The pagination at the bottom is not useful on mobile, but is still shown because css `is-hidden-mobile` applies to width, so portrait but not landscape.
- I can live with it as default, but **even when zooming in** (touchscreen-only feature unfortunately) the black bars remain which is really annoying.

So I'm trying to improve this but having trouble finding the correct CSS incantation as usual :D
