### ISSUE TITLE
Bug: translation keys using ticks (`) instead of quotes are not extracted

### ISSUE THREAD

**Issue by brunobesson** [c2corg/c2c_ui#1911]

**Comment by brunobesson** [comment]
Fixed by https://github.com/c2corg/c2c_ui/commit/6fa176ef5f21a19e7ea2dada55182224eb577233

**Comment by cbeauchesne** [comment]
> my fix is a simple ones that assumes that a dollar means there is a variable interpolation, so I exclude it.

I missed that part of your fix ^^ So yes, as far as I can understand it, it should be ok.

Being the devil's advocate, I would say that using template litterals without any placeholders instead of raw strings is a bad code pattern. But it' definitly not a big deal, and as the new regex are not executed on runtime, so ok for me :+1:

**Comment by brunobesson** [comment]
> Being the devil's advocate, I would say that using template litterals without any placeholders instead of raw strings is a bad code pattern

I agree with you with the exception of escaping simple quotes: it's far nicer to read

```js
const a = `let's go`;
```
than
```js
const a = 'let\'s go';
```
