### ISSUE TITLE
Chinese

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/c2c_ui#2220]
Chinese is available on demo, prepare the PR on the UI

**Comment by hemind** [comment]
I am wondering any update on the adding Chinese content? I have already tested the demo and give some feedback, but do not hear from you for about 6 months.

**Comment by brunobesson** [comment]
Sorry if there was a failure in the communication and triaging of the issues, but it has been solved a few months ago and you can of course select chinese in the interface of https://www.camptocamp.org since then.

![image](https://user-images.githubusercontent.com/2234024/190856985-48adec2d-e6a7-4905-bec5-48ba6563668f.png)
![image](https://user-images.githubusercontent.com/2234024/190857003-ff511601-1751-4fb2-8121-4aff02c75c73.png)

**Comment by hemind** [comment]
Thanks for the developers. The Chinese UI is already done and works well! I am just wondering the ability to add Chinese content, that means when adding content, select the language of my writing to Chinese. Now there is the Chinese option, but when I try to add, it says there is some error.

![image](https://user-images.githubusercontent.com/7596172/190862483-2687de71-d702-497f-b233-3d6275b85d47.png)

**Comment by brunobesson** [comment]
Indeed, my bad, A PR was merged on the API side a year ago (https://github.com/c2corg/v6_api/pull/1127). I don't know why it is not working. @cbeauchesne do you have any idea?

**Comment by brunobesson** [comment]
Hi @hemind.
I have investigated the issue, and the problem was simply that database migration was not run. You are now able to add chinese content. Enjoy!

**Comment by hemind** [comment]
Great! Now I am able to add Chinese content, thanks a lot!
