### ISSUE TITLE
Question about way we handle version number 

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/c2c_ui#425]
As now, i've simply copy pasted a `package.json`template at the beginning of the project.

It includes a property `version`. But now, I am questionning my self if this is relevant in our use case : 

* our repo won't be released on npm, and will never be a dependancies
* having this version number in `package.json`need a commit to update it : 
  * with a branch + PR ? it's not efficient, because between the PR creation and the merge, repo can evolute.
  * a direct commit on master ? maybe a less bad solution, but it's a commit on master. It's bad
* and as we use [github release tool](https://github.com/c2corg/c2c_ui/releases), we have two way to do the same job

I propose to simply not specify version number on package.json, and rely on github's release tool to handle version numbers.

@brunobesson, any POV on this ?

**Comment by brunobesson** [comment]
Sure, there is no absolute need to refer to the project with a release version in the `package.json` file. Still, I think this is no hard task, and we should stick to this.

There is no evil in committing directly to master as long as this is justified. One could also use `npm version` tool instead of github to make a release.

**Comment by cbeauchesne** [comment]
Ok, let keep process like this so. Thank you
