### ISSUE TITLE
Do not display buttons on associated routes on article view

### ISSUE THREAD

**Issue by brunobesson** [c2corg/c2c_ui#467]
E.g. https://www.camptocamp.org/articles/219828/fr/mobilite-douce-sur-camptocamp

![image](https://user-images.githubusercontent.com/2234024/55590106-46d73100-5732-11e9-9156-f04d9a47a6a0.png)

**Comment by cbeauchesne** [comment]
Actually, on this example, there isn't any route associated to this article : 

![image](https://user-images.githubusercontent.com/11915659/55617459-6dc64f00-5794-11e9-889b-f0b9c1964cc9.png)

If there isn't any associated route, we must display the box, because we need the "add new route" button.

**Comment by brunobesson** [comment]
Then there is some UI workk to do maybe.

But, the link "See all associated routes" does return many many results... https://www.camptocamp.org/routes?c=219828
(that's why I reported the problem, didn't pay attention that there were so many results...)

**Comment by cbeauchesne** [comment]
It's because API seems to not handle `&c` query. Actually, you see all existing routes with https://www.camptocamp.org/routes?c=219828

Until this is fixed on API, we should not display add button on this box, and in consequence, do not display the box if there is not association routes. Which means you are right from the beginning :)
