### ISSUE TITLE
Remove waypoint specific filter when waypoint type changes

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/c2c_ui#527]
See https://forum.camptocamp.org/t/nouvelle-interface-bugs-questions-suggestions/241148/151 

> il faudrait effacer les filtres spécifiques à un type de wp lorsqu'on arrête de filtrer sur lui.

**Comment by cbeauchesne** [comment]
Even if I'm not sure it's a good idea (what about the typeA then typeB, and back to typeA situation? you'll lost filter on typeA).

A better analysis of backend is necessary. But it's quite easy, and a good improvment, so keep it.

**Comment by AntoineMarnat** [comment]
The problem is that if you have a filter depending on type A only, and then change to type B, you have no results and can not desactivate the filter without reactivating type A. 

For example, if you look for showshoing routes, and look at grades R1 to R3. Then you select iceclimbing routes and have no results. To remove the filter on snowshoe grade you have to first reactivate snowshoing (and remember it!).
