### ISSUE TITLE
Feature: quality field mode

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/c2c_ui#992]
**Community discussion about this feature (mandatory)**

https://forum.camptocamp.org/t/vote-champ-completude-qualite/253410

Discussion include the specification and the vote

**Comment by asaunier** [comment]
Perhaps already known/discussed/reported somewhere but I have noticed the quality field is shared among all the linguistic versions of a given document.
It seems an issue in the API, as the ``quality`` attribute is part of the generic ``Document`` model:
https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/document.py#L43-L61

That does not make sense as a document may have a very good version in a language but be very poor in another one. Eg.
* https://www.camptocamp.org/waypoints/113031/fr/cabane-monte-leone-cas => FR = good
* https://www.camptocamp.org/waypoints/113031/de/monte-leone-hutte-sac => DE = draft (but marked as good because of the FR version). If switching down to draft, the FR version is made "draft" as well :/

There is an (old) API issue available at https://github.com/c2corg/v6_api/issues/701
